# Generated by Django 2.2 on 2019-05-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0002_auto_20190511_1106'),
    ]

    operations = [
    ]
