# Generated by Django 2.2 on 2019-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0003_auto_20190511_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': '学历', 'verbose_name_plural': '学历'},
        ),
        migrations.AlterModelOptions(
            name='stu_ate',
            options={'verbose_name': '学生状态(在校...)', 'verbose_name_plural': '学生状态(在校...)'},
        ),
        migrations.AlterModelOptions(
            name='zhicheng',
            options={'verbose_name': '职称', 'verbose_name_plural': '职称'},
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ManyToManyField(to='lg.Course', verbose_name='多对多关系'),
        ),
    ]
