# Generated by Django 2.2 on 2019-05-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0005_auto_20190511_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.BooleanField(default=True, verbose_name='性别男'),
        ),
        migrations.AlterField(
            model_name='student',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_num',
            field=models.BigIntegerField(verbose_name='学号'),
        ),
    ]
