# Generated by Django 2.2 on 2019-05-11 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0006_auto_20190511_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='local_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, unique=True, verbose_name='保存到本地的文件名'),
            preserve_default=False,
        ),
    ]
