# Generated by Django 2.2 on 2019-05-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0007_inform_local_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradetocourse',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='gradetocourse',
            name='grade_name',
        ),
        migrations.DeleteModel(
            name='Filed',
        ),
        migrations.DeleteModel(
            name='GradeToCourse',
        ),
    ]
