# Generated by Django 2.2 on 2019-05-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0008_auto_20190511_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='send_from_dpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发送教师对应部门', to='lg.Department', verbose_name='来自哪个部门'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='times',
            field=models.DateField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
