# Generated by Django 2.2 on 2019-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0009_auto_20190512_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='filed_name',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='上传文件的文件名'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='local_file',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='保存到本地的文件名'),
        ),
    ]
