# Generated by Django 2.2 on 2019-05-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0010_auto_20190513_1028'),
    ]

    operations = [
    ]
