# Generated by Django 2.2 on 2019-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0011_auto_20190513_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
