# Generated by Django 2.2 on 2019-05-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0012_inform_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='send_to_tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发送给哪个教师', to='lg.Teacher', verbose_name='发送给哪个教师'),
        ),
    ]
