# Generated by Django 2.1.1 on 2019-04-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashlibsalt',
            name='salt',
            field=models.CharField(max_length=300, verbose_name='加盐'),
        ),
    ]
