# Generated by Django 2.1.7 on 2019-05-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_user',
            name='acc_type',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='department',
        ),
        migrations.DeleteModel(
            name='Admin_user',
        ),
    ]
