# Generated by Django 2.1.7 on 2019-05-16 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190516_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Sex', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_name',
            field=models.CharField(max_length=16, verbose_name='姓名'),
        ),
    ]
