# Generated by Django 2.1.7 on 2019-05-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190516_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='department',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
