# Generated by Django 2.1.7 on 2019-05-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190515_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='call',
        ),
        migrations.DeleteModel(
            name='ZhiCheng',
        ),
    ]
