# Generated by Django 2.1.1 on 2019-04-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190422_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerfirst',
            name='student_account_number',
            field=models.CharField(default=1, max_length=13, unique=True, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerfirst',
            name='student_password',
            field=models.CharField(default='123456', max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='registerfirst',
            name='student_username',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='账号'),
        ),
    ]
