# Generated by Django 2.1.7 on 2019-05-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190516_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=128, unique=True, verbose_name='班级名称')),
                ('course', models.ManyToManyField(to='Main.Course', verbose_name='课程与班级')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Major', verbose_name='班级所在系部')),
                ('teacher', models.ManyToManyField(to='Main.RegisterFirst', verbose_name='班级对应教师')),
            ],
            options={
                'verbose_name': '班级表',
                'verbose_name_plural': '班级表',
            },
        ),
    ]
