# Generated by Django 2.1.7 on 2019-05-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_grade'),
    ]

    operations = [
    ]
