# Generated by Django 2.1.7 on 2019-05-17 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20190516_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='send_from_tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_teacher', to='Main.RegisterFirst', verbose_name='来自'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='send_to_tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_teacher', to='Main.RegisterFirst', verbose_name='发送给哪个教师'),
        ),
    ]
