# Generated by Django 2.1.7 on 2019-05-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20190517_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='filed_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='上传文件的文件名'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='local_file',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='保存到本地的文件名'),
        ),
    ]
