# Generated by Django 2.1.7 on 2019-05-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20190517_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='acc_type',
            new_name='teacher_acc_type',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='teacher_address',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='birth',
            new_name='teacher_birth',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='call',
            new_name='teacher_call',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='education',
            new_name='teacher_education',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='gender',
            new_name='teacher_gender',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='real_name',
            new_name='teacher_real_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='first',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.RegisterFirst', verbose_name='教师姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
