# Generated by Django 2.1.7 on 2019-05-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20190517_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_acc_type',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_call',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_education',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_gender',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
