# Generated by Django 2.1.7 on 2019-05-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20190517_1247'),
    ]

    operations = [
    ]
