# Generated by Django 2.1.7 on 2019-05-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20190517_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_real_name', models.CharField(max_length=16, verbose_name='姓名')),
                ('teacher_birth', models.DateField(verbose_name='出生日期')),
                ('teacher_address', models.CharField(max_length=256, verbose_name='家庭地址')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.RegisterFirst', verbose_name='教师姓名')),
                ('teacher_acc_type', models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='Main.Account_type', verbose_name='账户类型')),
                ('teacher_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.ZhiCheng', verbose_name='职称')),
                ('teacher_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Education', verbose_name='学历')),
                ('teacher_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Sex', verbose_name='性别')),
            ],
            options={
                'verbose_name': '教师用户',
                'verbose_name_plural': '教师用户',
            },
        ),
    ]
