# Generated by Django 2.1.7 on 2019-05-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_teacher'),
    ]

    operations = [
    ]
